ERROR_CODES = {
    "AUTH_REQUIRED": "AUTH_REQUIRED",
    "AUTH_INVALID": "AUTH_INVALID",
    "RBAC_DENIED": "RBAC_DENIED",
    "PROXY_FILL_DENIED": "PROXY_FILL_DENIED",
    "VALIDATION_FAILED": "VALIDATION_FAILED",
    "NOT_FOUND": "NOT_FOUND",
    "TASK_NOT_OWNED": "TASK_NOT_OWNED",
    "TASK_NOT_OPEN": "TASK_NOT_OPEN",
    "TICKET_CLOSED_CONFLICT": "TICKET_CLOSED_CONFLICT",
    "STALE_VERSION": "STALE_VERSION",
    "RATE_LIMITED": "RATE_LIMITED",
    "INTERNAL_ERROR": "INTERNAL_ERROR",
}
